import Head from "next/head";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";

import { BsFillJournalBookmarkFill } from "react-icons/bs";

import Layout from "../layout";
import Loading from "../components/loading";
import { dateToBeutify } from "../helpers";

export default function Home() {
  const router = useRouter();
  const [quizes, setQuizes] = useState([]);
  const [loading, setLoading] = useState(false);

  const loadQuizes = async () => {
    try {
      setLoading(true);
      const response = await fetch("api/quiz", {
        method: "POST",
        mode : 'no-cors',
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ mode: 3 }),
      });

      if (!response.ok) throw new Error("Can't Retrieve Quizes", { cause: response });

      const data = await response.json();

      setQuizes(data);
    } catch (e) {
      console.log(e);
    }
    setLoading(false);
  };

  useEffect(() => {
    loadQuizes();
  }, []);

  return (
    <>
      <Head>
        <title>Polka Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen mx-24 mt-12 font-andika text-2xl md:mt-24">
        <p className=""></p>

        <div className="flex flex-wrap mt-4">
          <div className="flex w-full justify-center">
            <Loading loading={loading} />
          </div>
          {!loading &&
            quizes.map((q, idx) => (
              <div key={idx} className="p-2 w-1/3 ">
                <div onClick={()=>router.push(`/quiz?_qid=${q._id}`)} className="card p-4 bg-neutral hover:cursor-pointer duration-150 ease-in ring ring-base-100 hover:ring-accent">
                  <p className="text-lg flex items-center"><BsFillJournalBookmarkFill className="mr-2"/>{q.quizName}</p>
                  <p className="mt-4 text-xs">{dateToBeutify(q.cat)}</p>
                </div>
              </div>
            ))}
        </div>
      </main>
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
